'use strict';

var stateAbrevs = [
  'AL',
  'AK',
  'AS',
  'AZ',
  'AR',
  'CA',
  'CO',
  'CT',
  'DE',
  'DC',
  'FM',
  'FL',
  'GA',
  'GU',
  'HI',
  'ID',
  'IL',
  'IN',
  'IA',
  'KS',
  'KY',
  'LA',
  'ME',
  'MH',
  'MD',
  'MA',
  'MI',
  'MN',
  'MS',
  'MO',
  'MT',
  'NE',
  'NV',
  'NH',
  'NJ',
  'NM',
  'NY',
  'NC',
  'ND',
  'MP',
  'OH',
  'OK',
  'OR',
  'PW',
  'PA',
  'PR',
  'RI',
  'SC',
  'SD',
  'TN',
  'TX',
  'UT',
  'VT',
  'VI',
  'VA',
  'WA',
  'WV',
  'WI',
  'WY'
];

var countryNameToIsoCode = {
  'Afghanistan': 'AF',
  'Albania': 'AL',
  'Algeria': 'DZ',
  'American Samoa': 'AS',
  'Andorra': 'AD',
  'Angola': 'AO',
  'Anguilla': 'AI',
  'Antarctica': 'AQ',
  'Antigua and Barbuda': 'AG',
  'Argentina': 'AR',
  'Armenia': 'AM',
  'Aruba': 'AW',
  'Australia': 'AU',
  'Austria': 'AT',
  'Azerbaijan': 'AZ',
  'Bahamas': 'BS',
  'Bahrain': 'BH',
  'Bangladesh': 'BD',
  'Barbados': 'BB',
  'Belarus': 'BY',
  'Belgium': 'BE',
  'Belize': 'BZ',
  'Benin': 'BJ',
  'Bermuda': 'BM',
  'Bhutan': 'BT',
  'Bolivia, Plurinational State of': 'BO',
  'Bonaire, Sint Eustatius and Saba': 'BQ',
  'Bosnia and Herzegovina': 'BA',
  'Botswana': 'BW',
  'Bouvet Island': 'BV',
  'Brazil': 'BR',
  'British Indian Ocean Territory': 'IO',
  'Brunei Darussalam': 'BN',
  'Bulgaria': 'BG',
  'Burkina Faso': 'BF',
  'Burundi': 'BI',
  'Cambodia': 'KH',
  'Cameroon': 'CM',
  'Canada': 'CA',
  'Cape Verde': 'CV',
  'Cayman Islands': 'KY',
  'Central African Republic': 'CF',
  'Chad': 'TD',
  'Chile': 'CL',
  'China': 'CN',
  'Christmas Island': 'CX',
  'Cocos (Keeling) Islands': 'CC',
  'Colombia': 'CO',
  'Comoros': 'KM',
  'Congo': 'CG',
  'Congo, the Democratic Republic of the': 'CD',
  'Cook Islands': 'CK',
  'Costa Rica': 'CR',
  'Country name': 'Code',
  'Croatia': 'HR',
  'Cuba': 'CU',
  'Curaçao': 'CW',
  'Cyprus': 'CY',
  'Czech Republic': 'CZ',
  "Côte d'Ivoire": 'CI',
  'Denmark': 'DK',
  'Djibouti': 'DJ',
  'Dominica': 'DM',
  'Dominican Republic': 'DO',
  'Ecuador': 'EC',
  'Egypt': 'EG',
  'El Salvador': 'SV',
  'Equatorial Guinea': 'GQ',
  'Eritrea': 'ER',
  'Estonia': 'EE',
  'Ethiopia': 'ET',
  'Falkland Islands (Malvinas)': 'FK',
  'Faroe Islands': 'FO',
  'Fiji': 'FJ',
  'Finland': 'FI',
  'France': 'FR',
  'French Guiana': 'GF',
  'French Polynesia': 'PF',
  'French Southern Territories': 'TF',
  'Gabon': 'GA',
  'Gambia': 'GM',
  'Georgia': 'GE',
  'Germany': 'DE',
  'Ghana': 'GH',
  'Gibraltar': 'GI',
  'Greece': 'GR',
  'Greenland': 'GL',
  'Grenada': 'GD',
  'Guadeloupe': 'GP',
  'Guam': 'GU',
  'Guatemala': 'GT',
  'Guernsey': 'GG',
  'Guinea': 'GN',
  'Guinea-Bissau': 'GW',
  'Guyana': 'GY',
  'Haiti': 'HT',
  'Heard Island and McDonald Islands': 'HM',
  'Holy See (Vatican City State)': 'VA',
  'Honduras': 'HN',
  'Hong Kong': 'HK',
  'Hungary': 'HU',
  'ISO 3166-2:GB': '(.uk)',
  'Iceland': 'IS',
  'India': 'IN',
  'Indonesia': 'ID',
  'Iran, Islamic Republic of': 'IR',
  'Iraq': 'IQ',
  'Ireland': 'IE',
  'Isle of Man': 'IM',
  'Israel': 'IL',
  'Italy': 'IT',
  'Jamaica': 'JM',
  'Japan': 'JP',
  'Jersey': 'JE',
  'Jordan': 'JO',
  'Kazakhstan': 'KZ',
  'Kenya': 'KE',
  'Kiribati': 'KI',
  "Korea, Democratic People's Republic of": 'KP',
  'Korea, Republic of': 'KR',
  'Kuwait': 'KW',
  'Kyrgyzstan': 'KG',
  "Lao People's Democratic Republic": 'LA',
  'Latvia': 'LV',
  'Lebanon': 'LB',
  'Lesotho': 'LS',
  'Liberia': 'LR',
  'Libya': 'LY',
  'Liechtenstein': 'LI',
  'Lithuania': 'LT',
  'Luxembourg': 'LU',
  'Macao': 'MO',
  'Macedonia, the former Yugoslav Republic of': 'MK',
  'Madagascar': 'MG',
  'Malawi': 'MW',
  'Malaysia': 'MY',
  'Maldives': 'MV',
  'Mali': 'ML',
  'Malta': 'MT',
  'Marshall Islands': 'MH',
  'Martinique': 'MQ',
  'Mauritania': 'MR',
  'Mauritius': 'MU',
  'Mayotte': 'YT',
  'Mexico': 'MX',
  'Micronesia, Federated States of': 'FM',
  'Moldova, Republic of': 'MD',
  'Monaco': 'MC',
  'Mongolia': 'MN',
  'Montenegro': 'ME',
  'Montserrat': 'MS',
  'Morocco': 'MA',
  'Mozambique': 'MZ',
  'Myanmar': 'MM',
  'Namibia': 'NA',
  'Nauru': 'NR',
  'Nepal': 'NP',
  'Netherlands': 'NL',
  'New Caledonia': 'NC',
  'New Zealand': 'NZ',
  'Nicaragua': 'NI',
  'Niger': 'NE',
  'Nigeria': 'NG',
  'Niue': 'NU',
  'Norfolk Island': 'NF',
  'Northern Mariana Islands': 'MP',
  'Norway': 'NO',
  'Oman': 'OM',
  'Pakistan': 'PK',
  'Palau': 'PW',
  'Palestine, State of': 'PS',
  'Panama': 'PA',
  'Papua New Guinea': 'PG',
  'Paraguay': 'PY',
  'Peru': 'PE',
  'Philippines': 'PH',
  'Pitcairn': 'PN',
  'Poland': 'PL',
  'Portugal': 'PT',
  'Puerto Rico': 'PR',
  'Qatar': 'QA',
  'Romania': 'RO',
  'Russian Federation': 'RU',
  'Rwanda': 'RW',
  'Réunion': 'RE',
  'Saint Barthélemy': 'BL',
  'Saint Helena, Ascension and Tristan da Cunha': 'SH',
  'Saint Kitts and Nevis': 'KN',
  'Saint Lucia': 'LC',
  'Saint Martin (French part)': 'MF',
  'Saint Pierre and Miquelon': 'PM',
  'Saint Vincent and the Grenadines': 'VC',
  'Samoa': 'WS',
  'San Marino': 'SM',
  'Sao Tome and Principe': 'ST',
  'Saudi Arabia': 'SA',
  'Senegal': 'SN',
  'Serbia': 'RS',
  'Seychelles': 'SC',
  'Sierra Leone': 'SL',
  'Singapore': 'SG',
  'Sint Maarten (Dutch part)': 'SX',
  'Slovakia': 'SK',
  'Slovenia': 'SI',
  'Solomon Islands': 'SB',
  'Somalia': 'SO',
  'South Africa': 'ZA',
  'South Georgia and the South Sandwich Islands': 'GS',
  'South Sudan': 'SS',
  'Spain': 'ES',
  'Sri Lanka': 'LK',
  'Sudan': 'SD',
  'Suriname': 'SR',
  'Svalbard and Jan Mayen': 'SJ',
  'Swaziland': 'SZ',
  'Sweden': 'SE',
  'Switzerland': 'CH',
  'Syrian Arab Republic': 'SY',
  'Taiwan, Province of China': 'TW',
  'Tajikistan': 'TJ',
  'Tanzania, United Republic of': 'TZ',
  'Thailand': 'TH',
  'Timor-Leste': 'TL',
  'Togo': 'TG',
  'Tokelau': 'TK',
  'Tonga': 'TO',
  'Trinidad and Tobago': 'TT',
  'Tunisia': 'TN',
  'Turkey': 'TR',
  'Turkmenistan': 'TM',
  'Turks and Caicos Islands': 'TC',
  'Tuvalu': 'TV',
  'Uganda': 'UG',
  'Ukraine': 'UA',
  'United Arab Emirates': 'AE',
  'United Kingdom': 'GB',
  'United States': 'US',
  'United States Minor Outlying Islands': 'UM',
  'Uruguay': 'UY',
  'Uzbekistan': 'UZ',
  'Vanuatu': 'VU',
  'Venezuela, Bolivarian Republic of': 'VE',
  'Viet Nam': 'VN',
  'Virgin Islands, British': 'VG',
  'Virgin Islands, U.S.': 'VI',
  'Wallis and Futuna': 'WF',
  'Western Sahara': 'EH',
  'Yemen': 'YE',
  'Zambia': 'ZM',
  'Zimbabwe': 'ZW',
  'Åland Islands': 'AX'
};

var phoneCodes = {
  "AC": "+247",
  "AD": "+376",
  "AE": "+971",
  "AF": "+93",
  "AG": "+1268",
  "AI": "+1264",
  "AL": "+355",
  "AM": "+374",
  "AN": "+599",
  "AO": "+244",
  "AR": "+54",
  "AS": "+1684",
  "AT": "+43",
  "AU": "+61",
  "AW": "+297",
  "AX": "+35818",
  "AZ": "+994",
  "BA": "+387",
  "BB": "+1246",
  "BD": "+880",
  "BE": "+32",
  "BF": "+226",
  "BG": "+359",
  "BH": "+973",
  "BI": "+257",
  "BJ": "+229",
  "BM": "+1441",
  "BN": "+673",
  "BO": "+591",
  "BR": "+55",
  "BS": "+1242",
  "BT": "+975",
  "BW": "+267",
  "BY": "+375",
  "BZ": "+501",
  "CA": "+1",
  "CC": "+61",
  "CD": "+243",
  "CF": "+236",
  "CG": "+242",
  "CH": "+41",
  "CI": "+225",
  "CK": "+682",
  "CL": "+56",
  "CM": "+237",
  "CN": "+86",
  "CO": "+57",
  "CR": "+506",
  "CS": "+381",
  "CU": "+53",
  "CV": "+238",
  "CX": "+61",
  "CY": "+357",
  "CZ": "+420",
  "DE": "+49",
  "DJ": "+253",
  "DK": "+45",
  "DM": "+1767",
  "DO": "+1809", // and 1829?
  "DZ": "+213",
  "EC": "+593",
  "EE": "+372",
  "EG": "+20",
  "EH": "+212",
  "ER": "+291",
  "ES": "+34",
  "ET": "+251",
  "FI": "+358",
  "FJ": "+679",
  "FK": "+500",
  "FM": "+691",
  "FO": "+298",
  "FR": "+33",
  "GA": "+241",
  "GB": "+44",
  "GD": "+1473",
  "GE": "+995",
  "GF": "+594",
  "GG": "+44",
  "GH": "+233",
  "GI": "+350",
  "GL": "+299",
  "GM": "+220",
  "GN": "+224",
  "GP": "+590",
  "GQ": "+240",
  "GR": "+30",
  "GT": "+502",
  "GU": "+1671",
  "GW": "+245",
  "GY": "+592",
  "HK": "+852",
  "HN": "+504",
  "HR": "+385",
  "HT": "+509",
  "HU": "+36",
  "ID": "+62",
  "IE": "+353",
  "IL": "+972",
  "IM": "+44",
  "IN": "+91",
  "IO": "+246",
  "IQ": "+964",
  "IR": "+98",
  "IS": "+354",
  "IT": "+39",
  "JE": "+44",
  "JM": "+1876",
  "JO": "+962",
  "JP": "+81",
  "KE": "+254",
  "KG": "+996",
  "KH": "+855",
  "KI": "+686",
  "KM": "+269",
  "KN": "+1869",
  "KP": "+850",
  "KR": "+82",
  "KW": "+965",
  "KY": "+1345",
  "KZ": "+7",
  "LA": "+856",
  "LB": "+961",
  "LC": "+1758",
  "LI": "+423",
  "LK": "+94",
  "LR": "+231",
  "LS": "+266",
  "LT": "+370",
  "LU": "+352",
  "LV": "+371",
  "LY": "+218",
  "MA": "+212",
  "MC": "+377",
  "MD": "+373",
  "ME": "+382",
  "MG": "+261",
  "MH": "+692",
  "MK": "+389",
  "ML": "+223",
  "MM": "+95",
  "MN": "+976",
  "MO": "+853",
  "MP": "+1670",
  "MQ": "+596",
  "MR": "+222",
  "MS": "+1664",
  "MT": "+356",
  "MU": "+230",
  "MV": "+960",
  "MW": "+265",
  "MX": "+52",
  "MY": "+60",
  "MZ": "+258",
  "NA": "+264",
  "NC": "+687",
  "NE": "+227",
  "NF": "+672",
  "NG": "+234",
  "NI": "+505",
  "NL": "+31",
  "NO": "+47",
  "NP": "+977",
  "NR": "+674",
  "NU": "+683",
  "NZ": "+64",
  "OM": "+968",
  "PA": "+507",
  "PE": "+51",
  "PF": "+689",
  "PG": "+675",
  "PH": "+63",
  "PK": "+92",
  "PL": "+48",
  "PM": "+508",
  "PR": "+1787", // and 1939 ?
  "PS": "+970",
  "PT": "+351",
  "PW": "+680",
  "PY": "+595",
  "QA": "+974",
  "RE": "+262",
  "RO": "+40",
  "RS": "+381",
  "RU": "+7",
  "RW": "+250",
  "SA": "+966",
  "SB": "+677",
  "SC": "+248",
  "SD": "+249",
  "SE": "+46",
  "SG": "+65",
  "SH": "+290",
  "SI": "+386",
  "SJ": "+47",
  "SK": "+421",
  "SL": "+232",
  "SM": "+378",
  "SN": "+221",
  "SO": "+252",
  "SR": "+597",
  "ST": "+239",
  "SV": "+503",
  "SY": "+963",
  "SZ": "+268",
  "TA": "+290",
  "TC": "+1649",
  "TD": "+235",
  "TG": "+228",
  "TH": "+66",
  "TJ": "+992",
  "TK": "+690",
  "TL": "+670",
  "TM": "+993",
  "TN": "+216",
  "TO": "+676",
  "TR": "+90",
  "TT": "+1868",
  "TV": "+688",
  "TW": "+886",
  "TZ": "+255",
  "UA": "+380",
  "UG": "+256",
  "US": "+1",
  "UY": "+598",
  "UZ": "+998",
  "VA": "+379",
  "VC": "+1784",
  "VE": "+58",
  "VG": "+1284",
  "VI": "+1-340",
  "VN": "+84",
  "VU": "+678",
  "WF": "+681",
  "WS": "+685",
  "YE": "+967",
  "YT": "+262",
  "ZA": "+27",
  "ZM": "+260",
  "ZW": "+263"
}

module.exports = {
  phoneCodes, 
  countryNameToIsoCode, 
  stateAbrevs
}